Update and rename label_enforcement.yml to label-enforcement.yml

diff --git a/.github/workflows/label-enforcement.yml b/.github/workflows/label-enforcement.yml
--- a/.github/workflows/label-enforcement.yml
+++ b/.github/workflows/label-enforcement.yml
@@ -14,4 +14,8 @@ jobs:
 
     steps:
       - name: test
-        run: if [[ "${{ env.LABELS }}" == "[]" ]]; then exit 1; fi
+        run: |
+          if [[ "${{ env.LABELS }}" == "[]" ]]; then
+            echo "::error::No label set on the pull request"
+            exit 1
+          fi
